# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
# only run on changes to main. Use main or master depending on whatever your default branch is called.
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
      with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
    - name: Build with Jekyll
        # Outputs to the './_site' directory by default
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production
    - name: Install deps and build
      run: |
        bundle exec jekyll build --incremental --destination public  
    # When the dist_dir is ready, deploy it to neocities
    - name: Deploy to Neocities
      # Don't use master, use a full 40 character commit hash, e.g.,
      # jonchang/deploy-neocities@deadbeef...
      uses: jonchang/deploy-neocities@master
      with:
        # Required, to access Neocities API.
        # https://neocities.org/settings
        # Set in Settings -> Secrets
        key: ${{ secrets.NEOCITIES_API_KEY }}
        # Required, local directory to deploy to Neocities
        dir: _site
        # Optional, if true, delete remote files not present locally
        clean: false
   
